filebeat.inputs:
  - type: filestream
    id: system-logs
    enabled: true
    paths:
      - /var/log/syslog
      - /var/log/auth.log
      - /var/log/kern.log

  - type: filestream
    id: mysql-logs
    enabled: true
    paths:
      - /var/log/mysql/*.log

  - type: filestream
    id: docker-nginx
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
    parsers:
      - container: ~
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - drop_event:
          when:
            not:
              or:
                - contains:
                    container.name: proxy
                - contains:
                    container.name: logstash
                - contains:
                    container.name: kibana
                - contains:
                    container.name: elasticsearch
                - contains:
                    container.name: grafana
                - contains:
                    container.name: prometheus
                - contains:
                    container.name: wordpress

output.logstash:
  hosts: ["$server_ip:5044"]

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
